### ISSUE TITLE
Add router, bootstrap and navbar

### ISSUE THREAD

**Issue by jtodd0515** [jtodd0515/journal-app#3]
This is a multifaceted item, but doable since 2 of the 3 are chore-like more than development work.

## Acceptance criteria

- Add dependencies for react-router-dom
- Add dependencies for bootstrap / react-bootstrap
- Add a mobile responsive top navbar which contains: 
    - The app brand; this usually consists of a left side logo which is the app title and links to the app home page
    - Some links, which will be hidden on smaller screens, and be shown upon click of a hamburger icon. 
    - These navigation items are TBD so a couple placeholders are fine until ironed out. More discussion can happen around this.

**Comment by krab7191** [comment]
Per scrum discussion: remove bootstrap packages in favor of using Material UI
